/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const NoteType = IDL.Variant({
  'text' : IDL.Null,
  'checklist' : IDL.Null,
});
export const ChecklistItem = IDL.Record({
  'id' : IDL.Text,
  'checked' : IDL.Bool,
  'order' : IDL.Nat,
  'text' : IDL.Text,
});
export const Input__2 = IDL.Record({
  'title' : IDL.Text,
  'reminder' : IDL.Opt(IDL.Int),
  'body' : IDL.Text,
  'color' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'locked' : IDL.Bool,
  'noteType' : NoteType,
  'checklistItems' : IDL.Vec(ChecklistItem),
  'pinHash' : IDL.Opt(IDL.Text),
});
export const Note = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'reminder' : IDL.Opt(IDL.Int),
  'body' : IDL.Text,
  'createdAt' : IDL.Int,
  'color' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'locked' : IDL.Bool,
  'noteType' : NoteType,
  'updatedAt' : IDL.Int,
  'pinned' : IDL.Bool,
  'trashed' : IDL.Bool,
  'checklistItems' : IDL.Vec(ChecklistItem),
  'pinHash' : IDL.Opt(IDL.Text),
  'trashedAt' : IDL.Opt(IDL.Int),
});
export const Label = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'color' : IDL.Text,
});
export const LabelInput = IDL.Record({
  'name' : IDL.Text,
  'color' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const UserSettings = IDL.Record({
  'theme' : IDL.Text,
  'language' : IDL.Text,
  'viewMode' : IDL.Text,
  'defaultColor' : IDL.Text,
});
export const Input__1 = IDL.Record({
  'theme' : IDL.Text,
  'language' : IDL.Text,
  'viewMode' : IDL.Text,
  'defaultColor' : IDL.Text,
});
export const Input = IDL.Record({
  'title' : IDL.Text,
  'reminder' : IDL.Opt(IDL.Int),
  'body' : IDL.Text,
  'color' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'locked' : IDL.Bool,
  'pinned' : IDL.Bool,
  'checklistItems' : IDL.Vec(ChecklistItem),
  'pinHash' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'changeColor' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createLabel' : IDL.Func([LabelInput], [Label], []),
  'createNote' : IDL.Func([Input__2], [Note], []),
  'deleteLabel' : IDL.Func([IDL.Text], [], []),
  'deleteNote' : IDL.Func([IDL.Text], [], []),
  'duplicateNote' : IDL.Func([IDL.Text], [Note], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLabels' : IDL.Func([], [IDL.Vec(Label)], ['query']),
  'getNoteById' : IDL.Func([IDL.Text], [Note], ['query']),
  'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getSettings' : IDL.Func([], [UserSettings], []),
  'getTrashedNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'permanentlyDeleteNote' : IDL.Func([IDL.Text], [], []),
  'pinNote' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'restoreNote' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveSettings' : IDL.Func([Input__1], [UserSettings], []),
  'updateLabel' : IDL.Func([IDL.Text, LabelInput], [Label], []),
  'updateNote' : IDL.Func([IDL.Text, Input], [Note], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const NoteType = IDL.Variant({ 'text' : IDL.Null, 'checklist' : IDL.Null });
  const ChecklistItem = IDL.Record({
    'id' : IDL.Text,
    'checked' : IDL.Bool,
    'order' : IDL.Nat,
    'text' : IDL.Text,
  });
  const Input__2 = IDL.Record({
    'title' : IDL.Text,
    'reminder' : IDL.Opt(IDL.Int),
    'body' : IDL.Text,
    'color' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'locked' : IDL.Bool,
    'noteType' : NoteType,
    'checklistItems' : IDL.Vec(ChecklistItem),
    'pinHash' : IDL.Opt(IDL.Text),
  });
  const Note = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'reminder' : IDL.Opt(IDL.Int),
    'body' : IDL.Text,
    'createdAt' : IDL.Int,
    'color' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'locked' : IDL.Bool,
    'noteType' : NoteType,
    'updatedAt' : IDL.Int,
    'pinned' : IDL.Bool,
    'trashed' : IDL.Bool,
    'checklistItems' : IDL.Vec(ChecklistItem),
    'pinHash' : IDL.Opt(IDL.Text),
    'trashedAt' : IDL.Opt(IDL.Int),
  });
  const Label = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'color' : IDL.Text,
  });
  const LabelInput = IDL.Record({
    'name' : IDL.Text,
    'color' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const UserSettings = IDL.Record({
    'theme' : IDL.Text,
    'language' : IDL.Text,
    'viewMode' : IDL.Text,
    'defaultColor' : IDL.Text,
  });
  const Input__1 = IDL.Record({
    'theme' : IDL.Text,
    'language' : IDL.Text,
    'viewMode' : IDL.Text,
    'defaultColor' : IDL.Text,
  });
  const Input = IDL.Record({
    'title' : IDL.Text,
    'reminder' : IDL.Opt(IDL.Int),
    'body' : IDL.Text,
    'color' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'locked' : IDL.Bool,
    'pinned' : IDL.Bool,
    'checklistItems' : IDL.Vec(ChecklistItem),
    'pinHash' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'changeColor' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createLabel' : IDL.Func([LabelInput], [Label], []),
    'createNote' : IDL.Func([Input__2], [Note], []),
    'deleteLabel' : IDL.Func([IDL.Text], [], []),
    'deleteNote' : IDL.Func([IDL.Text], [], []),
    'duplicateNote' : IDL.Func([IDL.Text], [Note], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLabels' : IDL.Func([], [IDL.Vec(Label)], ['query']),
    'getNoteById' : IDL.Func([IDL.Text], [Note], ['query']),
    'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getSettings' : IDL.Func([], [UserSettings], []),
    'getTrashedNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'permanentlyDeleteNote' : IDL.Func([IDL.Text], [], []),
    'pinNote' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'restoreNote' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveSettings' : IDL.Func([Input__1], [UserSettings], []),
    'updateLabel' : IDL.Func([IDL.Text, LabelInput], [Label], []),
    'updateNote' : IDL.Func([IDL.Text, Input], [Note], []),
  });
};

export const init = ({ IDL }) => { return []; };
