/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChecklistItem {
  'id' : string,
  'checked' : boolean,
  'order' : bigint,
  'text' : string,
}
export interface Input {
  'title' : string,
  'reminder' : [] | [bigint],
  'body' : string,
  'color' : string,
  'tags' : Array<string>,
  'locked' : boolean,
  'pinned' : boolean,
  'checklistItems' : Array<ChecklistItem>,
  'pinHash' : [] | [string],
}
export interface Input__1 {
  'theme' : string,
  'language' : string,
  'viewMode' : string,
  'defaultColor' : string,
}
export interface Input__2 {
  'title' : string,
  'reminder' : [] | [bigint],
  'body' : string,
  'color' : string,
  'tags' : Array<string>,
  'locked' : boolean,
  'noteType' : NoteType,
  'checklistItems' : Array<ChecklistItem>,
  'pinHash' : [] | [string],
}
export interface Label {
  'id' : string,
  'name' : string,
  'color' : string,
}
export interface LabelInput {
  'name' : string,
  'color' : string,
}
export interface Note {
  'id' : string,
  'title' : string,
  'reminder' : [] | [bigint],
  'body' : string,
  'createdAt' : bigint,
  'color' : string,
  'tags' : Array<string>,
  'locked' : boolean,
  'noteType' : NoteType,
  'updatedAt' : bigint,
  'pinned' : boolean,
  'trashed' : boolean,
  'checklistItems' : Array<ChecklistItem>,
  'pinHash' : [] | [string],
  'trashedAt' : [] | [bigint],
}
export type NoteType = { 'text' : null } |
  { 'checklist' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSettings {
  'theme' : string,
  'language' : string,
  'viewMode' : string,
  'defaultColor' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'changeColor' : ActorMethod<[string, string], undefined>,
  'createLabel' : ActorMethod<[LabelInput], Label>,
  'createNote' : ActorMethod<[Input__2], Note>,
  'deleteLabel' : ActorMethod<[string], undefined>,
  'deleteNote' : ActorMethod<[string], undefined>,
  'duplicateNote' : ActorMethod<[string], Note>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLabels' : ActorMethod<[], Array<Label>>,
  'getNoteById' : ActorMethod<[string], Note>,
  'getNotes' : ActorMethod<[], Array<Note>>,
  'getSettings' : ActorMethod<[], UserSettings>,
  'getTrashedNotes' : ActorMethod<[], Array<Note>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'permanentlyDeleteNote' : ActorMethod<[string], undefined>,
  'pinNote' : ActorMethod<[string, boolean], undefined>,
  'restoreNote' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveSettings' : ActorMethod<[Input__1], UserSettings>,
  'updateLabel' : ActorMethod<[string, LabelInput], Label>,
  'updateNote' : ActorMethod<[string, Input], Note>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
