/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Input {
    title: string;
    reminder?: bigint;
    body: string;
    color: string;
    tags: Array<string>;
    locked: boolean;
    pinned: boolean;
    checklistItems: Array<ChecklistItem>;
    pinHash?: string;
}
export interface ChecklistItem {
    id: string;
    checked: boolean;
    order: bigint;
    text: string;
}
export interface Input__1 {
    theme: string;
    language: string;
    viewMode: string;
    defaultColor: string;
}
export interface UserSettings {
    theme: string;
    language: string;
    viewMode: string;
    defaultColor: string;
}
export interface Input__2 {
    title: string;
    reminder?: bigint;
    body: string;
    color: string;
    tags: Array<string>;
    locked: boolean;
    noteType: NoteType;
    checklistItems: Array<ChecklistItem>;
    pinHash?: string;
}
export interface UserProfile {
    name: string;
}
export interface Note {
    id: string;
    title: string;
    reminder?: bigint;
    body: string;
    createdAt: bigint;
    color: string;
    tags: Array<string>;
    locked: boolean;
    noteType: NoteType;
    updatedAt: bigint;
    pinned: boolean;
    trashed: boolean;
    checklistItems: Array<ChecklistItem>;
    pinHash?: string;
    trashedAt?: bigint;
}
export interface Label {
    id: string;
    name: string;
    color: string;
}
export interface LabelInput {
    name: string;
    color: string;
}
export enum NoteType {
    text = "text",
    checklist = "checklist"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    changeColor(id: string, color: string): Promise<void>;
    createNote(input: Input__2): Promise<Note>;
    deleteNote(id: string): Promise<void>;
    duplicateNote(id: string): Promise<Note>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getNoteById(id: string): Promise<Note>;
    getNotes(): Promise<Array<Note>>;
    getSettings(): Promise<UserSettings>;
    getTrashedNotes(): Promise<Array<Note>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    permanentlyDeleteNote(id: string): Promise<void>;
    pinNote(id: string, pinned: boolean): Promise<void>;
    restoreNote(id: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveSettings(input: Input__1): Promise<UserSettings>;
    updateNote(id: string, input: Input): Promise<Note>;
    getLabels(): Promise<Array<Label>>;
    createLabel(input: LabelInput): Promise<Label>;
    updateLabel(id: string, input: LabelInput): Promise<Label>;
    deleteLabel(id: string): Promise<void>;
}
import type { ChecklistItem as _ChecklistItem, Input as _Input, Input__2 as _Input__2, Note as _Note, NoteType as _NoteType, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async changeColor(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.changeColor(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeColor(arg0, arg1);
            return result;
        }
    }
    async createNote(arg0: Input__2): Promise<Note> {
        if (this.processError) {
            try {
                const result = await this.actor.createNote(to_candid_Input__2_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Note_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNote(to_candid_Input__2_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Note_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteNote(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNote(arg0);
            return result;
        }
    }
    async duplicateNote(arg0: string): Promise<Note> {
        if (this.processError) {
            try {
                const result = await this.actor.duplicateNote(arg0);
                return from_candid_Note_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.duplicateNote(arg0);
            return from_candid_Note_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNoteById(arg0: string): Promise<Note> {
        if (this.processError) {
            try {
                const result = await this.actor.getNoteById(arg0);
                return from_candid_Note_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNoteById(arg0);
            return from_candid_Note_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotes(): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotes();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotes();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSettings(): Promise<UserSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return result;
        }
    }
    async getTrashedNotes(): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrashedNotes();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrashedNotes();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async permanentlyDeleteNote(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.permanentlyDeleteNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.permanentlyDeleteNote(arg0);
            return result;
        }
    }
    async pinNote(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.pinNote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pinNote(arg0, arg1);
            return result;
        }
    }
    async restoreNote(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.restoreNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.restoreNote(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveSettings(arg0: Input__1): Promise<UserSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSettings(arg0);
            return result;
        }
    }
    async updateNote(arg0: string, arg1: Input): Promise<Note> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNote(arg0, to_candid_Input_n17(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Note_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNote(arg0, to_candid_Input_n17(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Note_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLabels(): Promise<Array<Label>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLabels();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLabels();
            return result;
        }
    }
    async createLabel(arg0: LabelInput): Promise<Label> {
        if (this.processError) {
            try {
                const result = await this.actor.createLabel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLabel(arg0);
            return result;
        }
    }
    async updateLabel(arg0: string, arg1: LabelInput): Promise<Label> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLabel(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLabel(arg0, arg1);
            return result;
        }
    }
    async deleteLabel(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLabel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLabel(arg0);
            return result;
        }
    }
}
function from_candid_NoteType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NoteType): NoteType {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Note_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Note): Note {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    reminder: [] | [bigint];
    body: string;
    createdAt: bigint;
    color: string;
    tags: Array<string>;
    locked: boolean;
    noteType: _NoteType;
    updatedAt: bigint;
    pinned: boolean;
    trashed: boolean;
    checklistItems: Array<_ChecklistItem>;
    pinHash: [] | [string];
    trashedAt: [] | [bigint];
}): {
    id: string;
    title: string;
    reminder?: bigint;
    body: string;
    createdAt: bigint;
    color: string;
    tags: Array<string>;
    locked: boolean;
    noteType: NoteType;
    updatedAt: bigint;
    pinned: boolean;
    trashed: boolean;
    checklistItems: Array<ChecklistItem>;
    pinHash?: string;
    trashedAt?: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        reminder: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.reminder)),
        body: value.body,
        createdAt: value.createdAt,
        color: value.color,
        tags: value.tags,
        locked: value.locked,
        noteType: from_candid_NoteType_n10(_uploadFile, _downloadFile, value.noteType),
        updatedAt: value.updatedAt,
        pinned: value.pinned,
        trashed: value.trashed,
        checklistItems: value.checklistItems,
        pinHash: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.pinHash)),
        trashedAt: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.trashedAt))
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    text: null;
} | {
    checklist: null;
}): NoteType {
    return "text" in value ? NoteType.text : "checklist" in value ? NoteType.checklist : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Note>): Array<Note> {
    return value.map((x)=>from_candid_Note_n7(_uploadFile, _downloadFile, x));
}
function to_candid_Input__2_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Input__2): _Input__2 {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Input_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Input): _Input {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_NoteType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NoteType): _NoteType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    reminder?: bigint;
    body: string;
    color: string;
    tags: Array<string>;
    locked: boolean;
    pinned: boolean;
    checklistItems: Array<ChecklistItem>;
    pinHash?: string;
}): {
    title: string;
    reminder: [] | [bigint];
    body: string;
    color: string;
    tags: Array<string>;
    locked: boolean;
    pinned: boolean;
    checklistItems: Array<_ChecklistItem>;
    pinHash: [] | [string];
} {
    return {
        title: value.title,
        reminder: value.reminder ? candid_some(value.reminder) : candid_none(),
        body: value.body,
        color: value.color,
        tags: value.tags,
        locked: value.locked,
        pinned: value.pinned,
        checklistItems: value.checklistItems,
        pinHash: value.pinHash ? candid_some(value.pinHash) : candid_none()
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    reminder?: bigint;
    body: string;
    color: string;
    tags: Array<string>;
    locked: boolean;
    noteType: NoteType;
    checklistItems: Array<ChecklistItem>;
    pinHash?: string;
}): {
    title: string;
    reminder: [] | [bigint];
    body: string;
    color: string;
    tags: Array<string>;
    locked: boolean;
    noteType: _NoteType;
    checklistItems: Array<_ChecklistItem>;
    pinHash: [] | [string];
} {
    return {
        title: value.title,
        reminder: value.reminder ? candid_some(value.reminder) : candid_none(),
        body: value.body,
        color: value.color,
        tags: value.tags,
        locked: value.locked,
        noteType: to_candid_NoteType_n5(_uploadFile, _downloadFile, value.noteType),
        checklistItems: value.checklistItems,
        pinHash: value.pinHash ? candid_some(value.pinHash) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NoteType): {
    text: null;
} | {
    checklist: null;
} {
    return value == NoteType.text ? {
        text: null
    } : value == NoteType.checklist ? {
        checklist: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
